package com.crownfall.realm.audio

import android.media.AudioAttributes
import android.media.AudioFormat
import android.media.AudioManager
import android.media.AudioTrack
import android.os.Build
import android.util.Log
import com.crownfall.realm.domain.audio.SoundEffect
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.Executors

/**
 * Plays the game's sounds with [AudioTrack] using PCM generated by
 * [SoundSynthesizer]. One-shot effects are mixed on a small thread pool so a
 * flurry of combat sounds never blocks the render thread, and each voice is
 * released as soon as it finishes.
 */
class SynthesizedAudioEngine : AudioEngine {

    private val cache = ConcurrentHashMap<SoundEffect, ShortArray>()
    private val voicePool = Executors.newFixedThreadPool(4) { runnable ->
        Thread(runnable, "crownfall-audio").apply { isDaemon = true }
    }
    private val musicPool = Executors.newSingleThreadExecutor { runnable ->
        Thread(runnable, "crownfall-music").apply { isDaemon = true }
    }

    @Volatile
    private var musicVolume: Float = 0.6f

    @Volatile
    private var soundVolume: Float = 0.9f

    @Volatile
    private var combatSoundsEnabled: Boolean = true

    @Volatile
    private var musicTrack: AudioTrack? = null

    @Volatile
    private var musicLoopRequested: Boolean = false

    @Volatile
    private var released: Boolean = false

    /** Guards against starting a second streaming loop while one is alive. */
    private val musicRunning = java.util.concurrent.atomic.AtomicBoolean(false)

    override val isMusicPlaying: Boolean get() = musicTrack != null

    override fun play(effect: SoundEffect) {
        if (released) return
        if (effect.isCombatSound && !combatSoundsEnabled) return
        val volume = soundVolume
        if (volume <= 0.01f) return

        val samples = cache.getOrPut(effect) { SoundSynthesizer.samples(effect) }
        voicePool.execute { playOneShot(samples, volume) }
    }

    private fun playOneShot(samples: ShortArray, volume: Float) {
        if (released || samples.isEmpty()) return
        var track: AudioTrack? = null
        try {
            track = buildTrack(samples.size * 2, AudioTrack.MODE_STATIC)
            track.write(samples, 0, samples.size, AudioTrack.WRITE_BLOCKING)
            track.setVolume(volume.coerceIn(0f, 1f))
            track.play()
            val durationMs = samples.size * 1000L / SoundSynthesizer.SAMPLE_RATE
            Thread.sleep(durationMs + 40)
        } catch (error: Throwable) {
            Log.w(TAG, "Could not play sound effect", error)
        } finally {
            try {
                track?.stop()
            } catch (_: Throwable) {
            }
            try {
                track?.release()
            } catch (_: Throwable) {
            }
        }
    }

    override fun setMusicVolume(volume: Float) {
        musicVolume = volume.coerceIn(0f, 1f)
        val track = musicTrack
        if (track != null) {
            try {
                track.setVolume(musicVolume)
            } catch (_: Throwable) {
            }
        }
    }

    override fun setSoundVolume(volume: Float) {
        soundVolume = volume.coerceIn(0f, 1f)
    }

    override fun setCombatSoundsEnabled(enabled: Boolean) {
        combatSoundsEnabled = enabled
    }

    override fun startMusic() {
        if (released || musicVolume <= 0.01f) return
        if (!musicRunning.compareAndSet(false, true)) return
        musicLoopRequested = true
        musicPool.execute { musicLoop() }
    }

    /**
     * Streams the procedural loop in real time.
     *
     * The write loop is explicitly paced against the wall clock: a streaming
     * AudioTrack reports success even when nothing is being consumed (silent
     * output, emulator without an audio device), and without pacing that turns
     * into a busy-spin that pins a core. Pacing also keeps the music in sync
     * with real time on a healthy device.
     */
    private fun musicLoop() {
        val samples = MusicSynthesizer.loop()
        var track: AudioTrack? = null
        try {
            track = buildTrack(samples.size * 2, AudioTrack.MODE_STREAM)
            musicTrack = track
            track.setVolume(musicVolume)
            track.play()

            val startNanos = System.nanoTime()
            var framesWritten = 0L
            var offset = 0
            while (musicLoopRequested && !released) {
                val chunk = minOf(samples.size - offset, 4_096)
                val written = track.write(samples, offset, chunk, AudioTrack.WRITE_BLOCKING)
                if (written <= 0) break
                offset += written
                if (offset >= samples.size) offset = 0
                framesWritten += written

                val targetNanos = framesWritten * 1_000_000_000L / SoundSynthesizer.SAMPLE_RATE
                val aheadNanos = targetNanos - (System.nanoTime() - startNanos)
                if (aheadNanos > 5_000_000L) {
                    Thread.sleep(aheadNanos / 1_000_000L)
                }
            }
        } catch (interrupted: InterruptedException) {
            Thread.currentThread().interrupt()
        } catch (error: Throwable) {
            Log.w(TAG, "Could not stream music", error)
        } finally {
            musicTrack = null
            musicRunning.set(false)
            try {
                track?.stop()
            } catch (_: Throwable) {
            }
            try {
                track?.release()
            } catch (_: Throwable) {
            }
        }
    }

    override fun stopMusic() {
        musicLoopRequested = false
        val track = musicTrack
        try {
            track?.pause()
            track?.flush()
        } catch (_: Throwable) {
        }
    }

    override fun release() {
        released = true
        stopMusic()
        voicePool.shutdownNow()
        musicPool.shutdownNow()
        cache.clear()
    }

    private fun buildTrack(bufferSizeBytes: Int, mode: Int): AudioTrack {
        val format = AudioFormat.Builder()
            .setEncoding(AudioFormat.ENCODING_PCM_16BIT)
            .setSampleRate(SoundSynthesizer.SAMPLE_RATE)
            .setChannelMask(AudioFormat.CHANNEL_OUT_MONO)
            .build()
        val attributes = AudioAttributes.Builder()
            .setUsage(AudioAttributes.USAGE_GAME)
            .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
            .setLegacyStreamType(AudioManager.STREAM_MUSIC)
            .build()
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            AudioTrack.Builder()
                .setAudioAttributes(attributes)
                .setAudioFormat(format)
                .setBufferSizeInBytes(maxOf(bufferSizeBytes, MIN_BUFFER_BYTES))
                .setTransferMode(mode)
                .build()
        } else {
            @Suppress("DEPRECATION")
            AudioTrack(
                AudioManager.STREAM_MUSIC,
                SoundSynthesizer.SAMPLE_RATE,
                AudioFormat.CHANNEL_OUT_MONO,
                AudioFormat.ENCODING_PCM_16BIT,
                maxOf(bufferSizeBytes, MIN_BUFFER_BYTES),
                mode
            )
        }
    }

    private companion object {
        const val TAG = "CrownfallAudio"
        const val MIN_BUFFER_BYTES = 4096
    }
}
